### ISSUE TITLE
Terrain issue- Dirt is wonky, and doesn't convert\ spread grass

### ISSUE THREAD

**Issue by CaseHardened** [altmank/CaptainOfCheats#12]
Hello,

question 1)
Asking for a possible option to have the insta-dumped dirt, better spread grass.  Currently it is very wonky and I get weird grass lines and borders where the grass wont progress further past.

question 2)
Maybe there's a desire from more than just myself to have an option\selection instead of or not only dirt, but a grass dump option. This would allow for the bare dirt to till stay bare.  An option could be to allow the insta- dump dirt to spread grass like normal game mechanics.  Or possibly an option to manually select tiles with the terrain highlight tool allowing the player to convert selected tiles directly to grass.

Thanks for your time, and mod

**Comment by altmank** [comment]
I don't have any control over the grass spread mechanic as it relates to dumping terrain. Those are related but separate code concerns.

For question 2, to try and add an option to dump grass, for that I am leaving this issue open and labeling it as an enhancement request as that is something I can investigate if possible.

**Comment by CaseHardened** [comment]
[CURLAND CRAZY MOUNTAIN BUILD.zip](https://github.com/altmank/CaptainOfCheats/files/9226989/CURLAND.CRAZY.MOUNTAIN.BUILD.zip)

Awesome!  Thanks for looking into it.  I'm leaving my island for those interested in seeing the fun this mod is!

**Comment by altmank** [comment]
I took a look, terrain code is confusing. I wasn't able to figure out how to dump grass on my first attempt. Generally, this mod tries for the low hanging fruit so if an easy pass doesn't work, it is unlikely to get added. I unfortunately can't devote hours to debugging grass lol.

**Comment by CaseHardened** [comment]
I will just have to stick with insta- dumping a pile of dirt, then having the trucks dump it where it's
 needed.

**Comment by JonJoyce** [comment]
FYI this is working perfectly on version 0.5.0a - grass spreads perfectly, and fast.

**Comment by altmank** [comment]
Thanks @JonJoyce. Will close for now then.
