### ISSUE TITLE
Captainofcheat.dll

### ISSUE THREAD

**Issue by kirkirik** [altmank/CaptainOfCheats#14]
there is no .dll file on extraction?

**Comment by altmank** [comment]
Are you downloading the file titled CaptainOfCheats_v1.7.0.zip?

**Comment by kirkirik** [comment]
> Are you downloading the file titled CaptainOfCheats_v1.7.0.zip?

Yes. I'm new to github. The pull down menu on code and download zip file. The downloaded zip file " CaptainOfCheats-main.zip"
Extract it to documents/COI/mods

**Comment by lekkimsm2500** [comment]
> > Are you downloading the file titled CaptainOfCheats_v1.7.0.zip?
> 
> Yes. I'm new to github. The pull down menu on code and download zip file. The downloaded zip file " CaptainOfCheats-main.zip" Extract it to documents/COI/mods

When he asks if you downloaded "CaptainOfCheats_v1.7.0.zip", and you go "Yes, i downloaded CaptainOfCheats-main.zip", you just pointed out your own problem. You downloaded the wrong thing. Look at the right side of the page, where it says "Releases".

**Comment by kirkirik** [comment]
Yes I see my error. I'm sorry for wasting your time. This was the first time I downloaded something from github so my bad. Thanks for your help. :P
