### ISSUE TITLE
map borders

### ISSUE THREAD

**Issue by bennyb1971** [altmank/CaptainOfCheats#15]
is it possible to add a way to show the map borders? it would make it easier for people to dee to where they can dump and still be able to put a dock.

**Comment by altmank** [comment]
I do see some hooks related to rendering overlays on the ocean, so its within the realm of possibility that this could be used to do some kind of custom render of the map borders. 

Unfortunately, I don't have bandwidth to pursue things that are:

1. Not directly a cheat (this isn't a utility mod, but a cheat mod)
2. Are low ROI (at a glance, this is not a quick add) or have workarounds (you can just designate a dumping zone near the edge to get an idea of where the edges are already)
3. Are better targets to be implemented in base game as a feature

I do however appreciate you using the mod and reaching out.
