### ISSUE TITLE
hello error with version 0.4.10 game

### ISSUE THREAD

**Issue by emdas20** [altmank/CaptainOfCheats#16]
hello, thank you in advance for your work, I wanted to tell you that the trick produces an error with version 0.4.10 game, when the game is loading it crashes and reports errors and does not happen

**Comment by altmank** [comment]
Hi, 0.4.10 is in the experimental branch. COC is only maintained against the stable branch, so if it breaks COC once it is moved to the stable branch it will be resolved then.

**Comment by emdas20** [comment]
gracias
