### ISSUE TITLE
tree wood q-ty

### ISSUE THREAD

**Issue by Sijko** [altmank/CaptainOfCheats#19]
Could you make user selectable wood q-ty from a tree?
it's in the
Mafi.Base.Prototypes
{
	internal class TreesData : IModData
	{
		public void RegisterData(ProtoRegistrator registrator)
		{...
			TreeProto item = prototypesDb.Add<TreeProto>(new TreeProto(Ids.Trees.ConiferTree, orThrow.WithQuantity(20)...
			TreeProto item2 = prototypesDb.Add<TreeProto>(new TreeProto(Ids.Trees.BroadLeavesTree, orThrow.WithQuantity(20)
...

these two "20"'s

**Comment by altmank** [comment]
It would be a large departure from how the mod works currently. This would probably be a better fit for other mods that already modify protos (COI.Mod.Better does proto edits to add cheats). Captain of Cheats makes zero proto mods and hooks into the game manager classes/existing built-in cheats to introduce cheats.
