### ISSUE TITLE
Still encountering issue #18, clicking Storage god mode breaks the game

### ISSUE THREAD

**Issue by Rawhn** [altmank/CaptainOfCheats#20]
I have the same issues as explained in issue 18, but i am on version 1.8.1
https://github.com/altmank/CaptainOfCheats/issues/18

Clicking the storage god mode breaks the game, after this I can't really interact with anything at all. Things do not get highlighted and are not clickable.

Any suggestions?

**Comment by altmank** [comment]
Please attach your game log file.

**Comment by Rawhn** [comment]
Here you go :D
[22-08-28_19-48-23_6072.log](https://github.com/altmank/CaptainOfCheats/files/9440184/22-08-28_19-48-23_6072.log)

**Comment by altmank** [comment]
So your log file says you are on 0.4.10. But you're getting an error that looks related to the 0.4.11 experimental build. Please try two things:
- Have Steam verify your game files
- Try the 1.8.0 mod version, 1.8.1 was only created to try and preempt an issue in the upcoming 0.4.11 build and as far as I know has been stable before this point for several versions, so its a good fallback to try.

**Comment by altmank** [comment]
Also, see if 1.8.2 fixes your issue as well. https://github.com/altmank/CaptainOfCheats/releases/tag/v1.8.2
