### ISSUE TITLE
F8 - Cheat Menu Hotkey stopped working with latest release

### ISSUE THREAD

**Issue by deerbuster** [altmank/CaptainOfCheats#24]
##Note
Do not report bugs while using this mod with the experimental branch, this mod is not updated in response to experimental branch updates, it is only updated for stable branches.

**Describe the bug**
F8 no longer works with latest update.  Menu bar item works though

**Logs**
Please provide a log file from the directory %USERPROFILE%\Documents\Captain of Industry\Logs
[22-09-22_00-13-46_3522.log](https://github.com/altmank/CaptainOfCheats/files/9622421/22-09-22_00-13-46_3522.log)

**Comment by altmank** [comment]
I cannot reproduce. Sometimes issues with function keys are caused by the "F Lock" key. Can you check that toggling that key does not resolve your issue.

**Comment by deerbuster** [comment]
Yep, that's what it was...not sure why that was off...maybe the damn cat.  Thanks
