### ISSUE TITLE
i have this problem and no im not on experimental my beta's on steam is on 'NONE'

### ISSUE THREAD

**Issue by landerv123** [altmank/CaptainOfCheats#25]
![afbeelding](https://user-images.githubusercontent.com/28757584/191819667-e213d83e-e788-43b2-980c-c2e5bea34cb6.png)
 it started with the V0.4.12 even after updating it wit your new version i have no idee what it means or how to fix it.

**Comment by altmank** [comment]
Hi, as mentioned in the submit issue dialog, please submit a game log file for a game load where the issue occurs. A screen shot is not sufficient for me to investigate.

**Comment by altmank** [comment]
When you submit a bug report, the text that is already filled out has this text:
**Logs**
Please provide a log file from the directory %USERPROFILE%\Documents\Captain of Industry\Logs

If you cannot provide a log I cannot support your issue. Logs are always generated by the game every time you load it on your computer.

**Comment by landerv123** [comment]
[22-09-22_20-23-22_5202.log](https://github.com/altmank/CaptainOfCheats/files/9628522/22-09-22_20-23-22_5202.log)
i have found it was in 'UserProfile\OneDrive\Documenten\Captain of Industry\Logs'

**Comment by landerv123** [comment]
i have 2 location of captain of industry mods folder i have no idee what the difrence is
1='C:\Users\****\Documents\Captain of Industry\Mods'
2='C:\Users\****\OneDrive\Documenten\Captain of Industry\Mods'

**Comment by altmank** [comment]
Please install the latest version of the mod. Logs show you are running 1.8.2. The latest version is 1.9.0

**Comment by landerv123** [comment]
well it seems to work now so what shut i do with that random location where there is also a mod folder

**Comment by landerv123** [comment]
this location is the one that makes the mod work 'C:\Users*\OneDrive\Documenten\Captain of Industry\Mods'
but the other is where i replaced the old folder with the new because thats where i origanali placed it 'C:\Users*\Documents\Captain of Industry\Mods'

**Comment by altmank** [comment]
Feel free to do whatever you'd like with it. I can't answer why it exists unfortunately. Glad you got it working. Take care.
