### ISSUE TITLE
вылетает при запуске карты

### ISSUE THREAD

**Issue by bigznahar** [altmank/CaptainOfCheats#27]
##Note
При запуске карты 0.4.13 и мод CaptainOfCheats стабильный вылет в меню. При запуске карты без мода идет все нормально.

When launching the 0.4.13 map and the Captain Of Cheats mod, a stable departure in the menu. When launching the map without the mod, everything goes fine.
**Describe the bug**

**Logs**
[22-12-27_20-26-27_2929.log](https://github.com/altmank/CaptainOfCheats/files/10309869/22-12-27_20-26-27_2929.log)

Please provide a log file from the directory %USERPROFILE%\Documents\Captain of Industry\Logs

**Comment by altmank** [comment]
Hi, I'm not able to reproduce using latest version of game/mod. Can you provide exact steps to reproduce? If so, it may help me identify an issue, otherwise I may be unable to help as so far I cannot reproduce.
