### ISSUE TITLE
Storage God Mode Blocks building-to-building transfers

### ISSUE THREAD

**Issue by lekkimsm2500** [altmank/CaptainOfCheats#3]
Storage buildings with godmode enabled, and filled with a resource, are for some reason not able to transfer their resource through outputs, to a the inputs of a non-godmode'd storage building, if build right next to each other. And oppositely, a non-godmode'd building filled with a resource, cannot transfer its resources to a godmode building through out- and inputs, with an active keep empty function, and built right next to each other. 

A single unit of conveyor belt can be used to circumvent this, but not entirely ideal for small footprint setups, running on no power.

Thanks for the mod so far, works really well.

**Comment by altmank** [comment]
I can't say I've seen what you describe. I have enabled God mode in both
create and destroy mode embedded in existing building systems. This this
would mean transfer between God mode and non God mode stoages/systems. Can
you share screenshots or create a simple save that demonstrates?

**Comment by lekkimsm2500** [comment]
So i went back and double check, and it's very possible i've just been doing stuff in the wrong order, and i hadn't payed any attention to it.

It was working so well, i didn't realize i had three units in line, a godmode full, an intermediate and a godmode empty, and subsequently had been pausing them in the wrong order.

So that's entirely my fault, i apologize for bothering you.
Love the mod!

**Comment by altmank** [comment]
No worries. Glad it works as if it didn't I would have limited options to
fix easily as I'm just hooking into an existing cheat code created by Dev's
under the hood.
