### ISSUE TITLE
hy, on new update mod dont work.

### ISSUE THREAD

**Issue by bogdy0303** [altmank/CaptainOfCheats#32]
##Note
Do not report bugs while using this mod with the experimental branch, this mod is not updated in response to experimental branch updates, it is only updated for stable branches.

**Describe the bug**

**Logs**
Please provide a log file from the directory %USERPROFILE%\Documents\Captain of Industry\Logs

**Comment by bogdy0303** [comment]
hy, on new update V0.5.0. mod dont work

**Comment by bogdy0303** [comment]
hello, sorry to bother you, but it sais " Mods are disabled or not available.
i download the last version.
What i do wrong?

**Comment by goldhamster** [comment]
Maybe he has probs because there ist a new path for mods (.\AppData\Roaming\Captain of Industry)

**Comment by bogdy0303** [comment]
Thank you very much.
iam a big dumb. 
It work from there, thank you and sorry for bother you
