### ISSUE TITLE
Storage filling material feature

### ISSUE THREAD

**Issue by saifulazfar** [altmank/CaptainOfCheats#33]
note really a bug...just i believe before there are feature that auto fill storage by slide the slider on storage setting...but wonder if the feature are being removed or there are plan to add with compability with the new update...its hard to play without storage filling feature as i skipping much alot with mining/no truck and such

**Comment by altmank** [comment]
I'm not sure I am following completely but in general, all previous COC features were updated to work with the latest update. The only known change was that terrain modification lost the 'disable physics' feature. Please consider sharing more details or screenshots that may help me understand your issue.
