### ISSUE TITLE
Typo - vehicles tab, maintenance tooltip

### ISSUE THREAD

**Issue by JonJoyce** [altmank/CaptainOfCheats#36]
##Note
Do not report bugs while using this mod with the experimental branch, this mod is not updated in response to experimental branch updates, it is only updated for stable branches.

**Describe the bug**
Guessing this should be 'Off' not 'ff'
![image](https://github.com/altmank/CaptainOfCheats/assets/448438/50f753f8-6741-439a-9e76-940ccaeb92fb)

**Logs**
N/A

**Comment by altmank** [comment]
Fixed
