### ISSUE TITLE
Request - Instant Mode Trees

### ISSUE THREAD

**Issue by JonJoyce** [altmank/CaptainOfCheats#37]
Under 'Landmarks & Decorations' the two trees (fir/spruce) do not instant place when in Instant mode, not a big deal but if theres a way to update them to auto place/grow when placed in instant mode, that would be great. 

Worst case we can just storage god mode some saplings and a few instant tree planters...

**Comment by altmank** [comment]
Instant mode is a cheat feature provided by the developers. I have zero control over what it does, I just turn it on or off. Therefore I cannot modify it's behavior to meet your request.
