### ISSUE TITLE
Change terrain is blending instead of changing

### ISSUE THREAD

**Issue by JonJoyce** [altmank/CaptainOfCheats#38]
##Note
Do not report bugs while using this mod with the experimental branch, this mod is not updated in response to experimental branch updates, it is only updated for stable branches.

**Describe the bug**
Tried setting same layer as well as 1 & 2 layers above terrain i'm trying changing.
Not within tower control area.

![image](https://github.com/altmank/CaptainOfCheats/assets/448438/a22e758d-d7ca-497b-b5e2-546cbbab4983)
![image](https://github.com/altmank/CaptainOfCheats/assets/448438/d1d49174-f6ee-4973-9849-08faf04c0175)

at number 1, area was dirt, changing to slag.
at number 2, area was rock, changing to slag.

This is with the latest build of the mod.

**Logs**
Please provide a log file from the directory %USERPROFILE%\Documents\Captain of Industry\Logs

**Comment by JonJoyce** [comment]
I've just tried it on a different area and its working. 
The area reported on this issue was being driven over a lot at the time - perhaps its todo with it being 'disturbed' or not.

**Comment by altmank** [comment]
Its possible the disturbed effect will go away, let me know what you observe. I'm using one of their methods to 'convert' a layer from one material to another.

**Comment by JonJoyce** [comment]
Yeah, i've let saves run for several years, barriered off the area and the disturbed effect never disappears... even re-trying to change terrain does not improve it. Only work around is to insta mine and insta dump the affected areas.

**Comment by JonJoyce** [comment]
I've also noticed, if you change terrains once (say with the wrong material) and then change it again, you get the same affect,
