### ISSUE TITLE
[Feature request] half full or half empty in god mode storage

### ISSUE THREAD

**Issue by joejoe0243** [altmank/CaptainOfCheats#42]
Example, I have a concrete slab storage set to always full. When I destroy a building, concrete slabs returned. But it cannot be transferred to storage because storage is full. I know I can build another storage but sometimes it is not convenience.

It would be grateful if I can set god mode storage has some spaces left, half full or half empty is fine.

Thank you.

**Comment by altmank** [comment]
Unfortunately god storage mode is a feature implemented in the base game by developers, I only expose it as a button to click to turn it on for storages. I cannot customize its behavior in the current mod design as that code is not exposed in a way to override behavior.
