### ISSUE TITLE
Install instructions not up to date

### ISSUE THREAD

**Issue by gespensen** [altmank/CaptainOfCheats#43]
##Note
Up date instructions for latest release.

**Describe the bug**

**Logs**
Please provide a log file from the directory %USERPROFILE%\Documents\Captain of Industry\Logs

**Comment by altmank** [comment]
Hi, what are you calling out as not up to date? You didn't include any specifics about what you view as wrong in your issue. As far as I am aware current instructions are correct.

**Comment by altmank** [comment]
Closing as ticket has insufficient detail.

**Comment by altmank** [comment]
The path you provided is actually equivalent to the path in the mod instructions. You can validate this by pasting that path provided in the instructions into your folder address bar and seeing where it takes you. This path is dynamic so we use features of windows which represent that path dynamically.
