### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by boothy86** [altmank/CaptainOfCheats#44]
I seem to be having an issue with installing the mod I've followed it to the point but still don't seem to work my game is installed on one off my drives but the other part is on my main drive I even followed the youtube vid explaining how but I don't see the wheel at the bottom and it's enabled on the game it's self it's giving me an headache

**Comment by cinoche92** [comment]
Same issue

I dont see a .dll in the download, seems like the problem to me.

**Comment by altmank** [comment]
Current release files have been used by hundreds of people to install the mod. Please verify you are using the correct files, if you aren't sure seek out support from the modding channel on the COI Discord, plenty of people are willing to help with installation support there.
