### ISSUE TITLE
Mod don't load.

### ISSUE THREAD

**Issue by JohnFernandes1997** [altmank/CaptainOfCheats#45]
Hello, I have the steam version and I followed the "installation" instructions for the mod. However, when I launch the game, an error appears saying that it cannot be loaded. The game version is v0.5.3e. I already uninstalled and reinstalled the game, but it didn't work.

[Uploading 23-07-24_14-05-21_9340.log…]()

**Comment by altmank** [comment]
Unable to look at your log file, please try reuploading. No issues here loading latest mod on 0.5.3e

**Comment by BretBierle** [comment]
Still working on 0.5.3?

**Comment by BretBierle** [comment]
same here

**Comment by JohnFernandes1997** [comment]
[23-08-07_13-45-05_8254.log](https://github.com/altmank/CaptainOfCheats/files/12283130/23-08-07_13-45-05_8254.log)

**Comment by kernelplv** [comment]
Version 0.5.5. The mod is loading, but it’s impossible to call the menu. There is no button to call the cheat menu, the F8 key does not work.
[23-09-23_18-50-12_2397.log](https://github.com/altmank/CaptainOfCheats/files/12706854/23-09-23_18-50-12_2397.log)

**Comment by altmank** [comment]
No issues here loading the latest 0.5.5 game with v2.1. Mod menu opens and quick test of cheats shows as working. @kernelplv Your log if full of errors in the base game, no errors from my mod and is not reproducible on my side. Not sure how to help you here unfortunately.
