### ISSUE TITLE
[Feature request] Allow negative electricity generation

### ISSUE THREAD

**Issue by thirionlogan** [altmank/CaptainOfCheats#46]
Allow negative electricity generation so that power generator setups can be stress-tested

**Comment by altmank** [comment]
Hi, I'm currently maintaining this mod but not putting time into new features. If that changes in the future I'll take a look at this request. In the meantime, you may be able to find someone in the Discord willing to take this code and build a custom version with what you request.

**Comment by altmank** [comment]
@JamieRCHI 
App data can be remapped on windows, thus I use the path that includes the path variable %APPDATA%, you can actually type this whole path into windows explorer and it will take you to the correct directory as mapped on your system. So there is nothing incorrect about it.

%APPDATA%\Captain of Industry\Mod

**Comment by altmank** [comment]
Check out https://github.com/Keranik/COI-Extended releases for an alternate cheat mod, after the release today (see v3 in releases, this will no longer be maintained)
