### ISSUE TITLE
need to add functionality on existing saves

### ISSUE THREAD

**Issue by VerserVarlin** [altmank/CaptainOfCheats#47]
I'm over 700 years into my game save and a catastrophe hit my island while I was updating my power generation plant. I was hoping this mod would help me repair my save till It was back to being stable again, sadly from what I am reading on Reddit the mod only works on new saves. can you make it work on existing saves, please?

**Comment by altmank** [comment]
I think that limitation was removed many patches ago. So give it a try.

**Comment by VerserVarlin** [comment]
no, the f8 does not work and there is no ship wheel on the lower hotbar in existing saves

**Comment by altmank** [comment]
I don't see any issues on my side enabling my mod on a save that previously did not have it installed, so you're probably missing a step. Please seek out general mod support on the Discord, plenty of people can provide interactive help there.

![image](https://github.com/altmank/CaptainOfCheats/assets/22986384/c9e5a660-33b1-42f0-8e2f-2cdff93c0c04)
