### ISSUE TITLE
Missing .dll file

### ISSUE THREAD

**Issue by heyjude42** [altmank/CaptainOfCheats#5]
Mod seems to be missing the .dll file? Sorry if I am missing something obvious, but I cannot get the mod work - game log file states there is no .dll file available.

**Comment by altmank** [comment]
Hi. Please share you log file. Also, please read through the installation instructions carefully, almost every issue I've seen so far with mod loading is due to not following those directions explictly.

**Comment by heyjude42** [comment]
[22-06-18_04-22-45_5105.log](https://github.com/altmank/CaptainOfCheats/files/8930876/22-06-18_04-22-45_5105.log)

**Comment by altmank** [comment]
Thanks. If you navigate to D:\Documents\Captain of Industry\Mods\CaptainOfCheats\. Do you see a CaptainOfCheats.dll file there? if not, please download the mod release again and extract its files there. 

Should look like this in the CaptainOfCheats folder:
![image](https://user-images.githubusercontent.com/22986384/174389240-029de0cb-6d22-4b2f-8aca-e38091e7a2bf.png)

**Comment by heyjude42** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/107715597/174389388-b89f80f9-e610-4322-b5fa-996a53bf1921.png)
This is what I got when I extracted the zip - no .dll file

**Comment by heyjude42** [comment]
will try downloading and extracting again

**Comment by heyjude42** [comment]
worked out what it was - I downloaded the source file, not the finished file - my apologies and thanks for the fast help!

**Comment by altmank** [comment]
You're downloading the wrong zip. You're extracting the source file zip, not the compiled dll zip.

**Comment by altmank** [comment]
![image](https://user-images.githubusercontent.com/22986384/174390292-92d4d322-93f1-4b3e-9651-402bec198fb2.png)

**Comment by altmank** [comment]
Closing as problem was identified as user trying to extract the source code zips when the game expects compiled DLL files.
