### ISSUE TITLE
Truck Capacities Don't Reset

### ISSUE THREAD

**Issue by epoch18** [altmank/CaptainOfCheats#8]
Using the mod, under Vehicles menu I selected the +500% Truck Capacity Multiplier. Worked fine. 

After a bit, clicked the Reset button and no change. 

Thanks.

**Comment by altmank** [comment]
@epoch18 Can you provide your save file where you have a permanent +500% that you cannot reset?

**Comment by epoch18** [comment]
[22-07-02_16-17-46_1048-autosave.zip](https://github.com/altmank/CaptainOfCheats/files/9033842/22-07-02_16-17-46_1048-autosave.zip)

Pickups at 120
Large Trucks at 360

**Comment by epoch18** [comment]
Clicking +100 now sets (for example) trucks to 420 and +200% sets them to 480. Clicking either +500% or Reset puts it back to 360.

**Comment by altmank** [comment]
Fixed in commit ac399a3f

**Comment by altmank** [comment]
Hello, I cannot reproduce. Can you please provide additional information
that may help me reproduce the issue?
