### ISSUE TITLE
Suggestion: Disable or prevent "It's Over" when I run out of people.

### ISSUE THREAD

**Issue by JamieRCHI** [altmank/CaptainOfCheats#9]
Wasn't paying attention in the beginning. Started moving the people and got sidetracked.
Is this even possible? 
Probably should have left the game on pause.
Priority low?

**Comment by altmank** [comment]
Considering COC already has cheats to create infinite food to feed your population and cheats to directly add new population, prioritizing adding an additional mechanism here is unlikely at least from my perspective. I'm not opposed to others contributing to the project though. Closing ticket as not planned for the above reasons.
